title: chemotools
description: Chemotools integrates chemometrics with sklearn
theme: just-the-docs

# logo
logo: "/assets/images/logo_pixel.png"

favicon_ico: "/assets/images/icon_4.bmp"

markdown: kramdown
kramdown:
  parse_block_html: true


url: https://just-the-docs.github.io


color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    title: Highlight
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red